version: 2

sources:
  - name: dbt_dev
    tables:
      - name: stg_customers
      - name: stg_orders
      - name: stg_products
      - name: stg_sellers
      - name: stg_order_items
      - name: stg_order_payments
      - name: stg_order_reviews
      - name: stg_product_category_translations
      - name: stg_geolocation